### ISSUE TITLE
[feat] 프로필 모달 컴포넌트 생성

### ISSUE THREAD

**Issue by bananashow** [withfoodmate/frontend#29]
- 모달 컴포넌트 생성
- 사용자 mock data 생성

![image](https://github.com/withfoodmate/frontend/assets/85798544/8c95fd1c-fa05-4686-97de-378f5ac7f30c)

**Comment by oinochoe** [comment]
디자인 톤앤매너가 좀 더 강화 되면 좋겠어요. 
x버튼이 이 카드에서 가장 강조되어야 할 부분은 아닌데, 매우 강조되어있고, 닉네임, 이메일 등등은 너무 흐리게 처리되었고 하트는 좀 올드해보입니다 😄 
일식 중식 버튼의 색상과 하트의 색상이 너무나도 어울리지 않는 느낌이 있어요!

나중에 조금 더 다듬어보세요 😄 
디자인 템플릿을 많이 보면 도움될 것 같아요.
https://flowbite.com/docs/components/card/
![image](https://github.com/withfoodmate/frontend/assets/24869229/36b46677-959a-4699-8f1f-a5fa0fea63af)

**Comment by bananashow** [comment]
디자인 정말 어려운 것 같아요 🥲 디자인 수정하면서 코드 짜보겠습니다!
