### ISSUE TITLE
[feat] 모임 정보 - 신청 내역 페이지

### ISSUE THREAD

**Issue by bananashow** [withfoodmate/frontend#54]
- 신청 내역 (3개월 미만)
  - 필터링
    - 전체
    - 요청 수락
    - 요청 거절
    - 요청 대기중
    - 요청 취소

- 지난 모임
  - 3개월 미만 지난 모임을 보여줌
 
![image](https://github.com/withfoodmate/frontend/assets/85798544/f0361b40-bdde-4591-b242-149914118691)

**Comment by oinochoe** [comment]
뭔가 푸터 메뉴가 황토색인게..  골드 색상인지.. 여튼 전체 톤앤매너의 채도는 밝은 채도인데... 
중후한 맛이 나는 것도 아닌 것이.. 약간 올드한 티가 나요!

**Comment by oinochoe** [comment]
![image](https://github.com/withfoodmate/frontend/assets/24869229/37233148-48e2-43fc-8c8b-95f8096a53d6)

**Comment by oinochoe** [comment]
https://goddino.tistory.com/13

참고 해보시면 좋을 것 같아요.

**Comment by bananashow** [comment]
@oinochoe 푸터는 일단 넣지 않을 생각입니다 ㅎㅎ그 점도 여쭤보고 싶었는데, 보통 실무가 아닌 프로젝트 시 푸터를 넣나요?

**Comment by oinochoe** [comment]
@bananashow 실무가 아닌 프로젝트에 굳이 footer를 넣을 필요는 없지만, footer의 활용도가 높기 때문에 현업에서도 중요하게 생각하지 않을까 싶습니다 😃 

https://www.beusable.net/blog/?p=4391
footer의 효용가치.

쇼핑몰 같은 경우는 법적인 부분도 겹칩니다.
https://www.sixshop.com/official-blog/%EC%87%BC%ED%95%91%EB%AA%B0-%EC%B2%AB-%ED%99%94%EB%A9%B4%EC%97%90-%EB%B0%98%EB%93%9C%EC%8B%9C-%EB%85%B8%EC%B6%9C%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EB%B2%95%EC%A0%81-%ED%95%84%EC%88%98-%EC%A0%95%EB%B3%B4-qvl4so

**Comment by oinochoe** [comment]
@bananashow 네네 구현 먼저하시고 디자인 다듬으시죠 😄 화이팅~
